// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrX3gfGBvrTxHTwq7d2uAsa-Qu5ZDnnd4',
    appId: '1:302420738156:web:64e8a15b9b3d66cd5a9849',
    messagingSenderId: '302420738156',
    projectId: 'kitahack2026-c2a42',
    authDomain: 'kitahack2026-c2a42.firebaseapp.com',
    storageBucket: 'kitahack2026-c2a42.firebasestorage.app',
    measurementId: 'G-K91CD1ND7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXce7FFpIbUzS_eZ7IALr0DwyfQzSMC6I',
    appId: '1:302420738156:android:e9608f98251407435a9849',
    messagingSenderId: '302420738156',
    projectId: 'kitahack2026-c2a42',
    storageBucket: 'kitahack2026-c2a42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvfDIgncepmZqgp0w9r8fFn1Iu52syrPk',
    appId: '1:302420738156:ios:2a290749158fff605a9849',
    messagingSenderId: '302420738156',
    projectId: 'kitahack2026-c2a42',
    storageBucket: 'kitahack2026-c2a42.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvfDIgncepmZqgp0w9r8fFn1Iu52syrPk',
    appId: '1:302420738156:ios:2a290749158fff605a9849',
    messagingSenderId: '302420738156',
    projectId: 'kitahack2026-c2a42',
    storageBucket: 'kitahack2026-c2a42.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrX3gfGBvrTxHTwq7d2uAsa-Qu5ZDnnd4',
    appId: '1:302420738156:web:e6e2521c8c237bc25a9849',
    messagingSenderId: '302420738156',
    projectId: 'kitahack2026-c2a42',
    authDomain: 'kitahack2026-c2a42.firebaseapp.com',
    storageBucket: 'kitahack2026-c2a42.firebasestorage.app',
    measurementId: 'G-TEG5VJBSF0',
  );
}
